### ISSUE TITLE
File > Restart is not working as expected

### ISSUE THREAD

**Issue by MarcelStranak** [localstack/cockpit#1]
Hi,

Option under File > Restart does not work.  It just kills the LocalStack-Cockpit and does not start it again.
I am expecting that it should restart the program (stop the service and start anew).

![2022_03_16_opera_14_25_22_69](https://user-images.githubusercontent.com/97876429/158600004-232497f6-72ec-4788-8561-388359844047.gif)

**Comment by MarcelStranak** [comment]
Same thing happens when using the `Restart` button. 

![2023_01_10_LocalStack_Cockpit_17_02_02_556](https://user-images.githubusercontent.com/97876429/212037036-4f807087-4f5b-4cb4-bc46-084a41af3eb5.png)

**Comment by Pive01** [comment]
Closing as this project is now deprecated, please switch to use [LocalStack Desktop](https://github.com/localstack/localstack-desktop) instead.
