### ISSUE TITLE
win executable triggers security warnings

### ISSUE THREAD

**Issue by christian-korneck** [localstack/cockpit#10]
this isn't critical (more like a friendly suggestion): On my Windows machine `LocalStack Cockpit 0.1.1.exe` triggered mutliple security popups and asked for excemptions (Browser after download, Windows SmartShield/Defender, Anti Malware). I don't mind, but in managed environments this can be a hassle.

I believe this would much improve if the installer and the binaries that it exctracts were codesigned with a cert from a trusted CA.

**Comment by MarcelStranak** [comment]
Thank you, we have added this in our [docs](https://docs.localstack.cloud/user-guide/tools/cockpit/#known-issues) pages.
We will take this into consideration in the upcoming releases.
