### ISSUE TITLE
Checking LocalStack Runtime Status error with Ubuntu

### ISSUE THREAD

**Issue by khaldelbadawy** [localstack/cockpit#11]
Hi,

I am getting error with Checking LocalStack Runtime Status that Docker is not available although it is available according to the screenshot

![Selection_003](https://user-images.githubusercontent.com/25727255/183906143-b773d111-d8e2-4934-ba6f-d37c9a0ff095.png)

**Comment by FelipeTomazEC** [comment]
I'm getting the same error. Does anyone know what to do to solve this issue?
Thnx!

**Comment by tandibar** [comment]
Same error here with Ubuntu 20.04 and Docker Desktop. It seems to me, that python docker SDK cannot detect installed docker.

**Comment by MarcelStranak** [comment]
Hello @khaldelbadawy, @FelipeTomazEC, @tandibar,
We have a new version of LocalStack Cockpit which should resolve this issue. Please download the new version and give it another try. Thank you.
