### ISSUE TITLE
Issue in initializing cockpit on MacOS

### ISSUE THREAD

**Issue by Jay1305** [localstack/cockpit#13]
Hi Localstack Team -

Mac Os - 12.6 Monterey Intel
Cockpit version - LocalStack Cockpit-0.1.1.dmg 
I downloaded and without moving it to applications, have put app in my personal folder.
It can recognize the docker from outside but cannot from inside localstack binary. I do not have docker desktop but using docker with lima and it works perfectly fine for every other application.
Restart doesn't work and if I try to close the application by x, it doesn't close and have to close using activity monitor.
I can run localstack using docker/pip without issues and can play with demo - [localstack-demo](https://www.github.com/localstack/localstack-demo.git)

It is just not this application :(. 

![image](https://user-images.githubusercontent.com/31636584/205202473-56605e56-82ee-4d57-a33b-c13ead0cf98e.png)

**Comment by Jay1305** [comment]
It feels like the issue is similar to https://github.com/microsoft/vscode-docker/issues/2509#issuecomment-740781160, where the docker path is not receiving to underlying process.

**Comment by Pive01** [comment]
Closing as this project is now deprecated, please switch to use [LocalStack Desktop](https://github.com/localstack/localstack-desktop) instead.
