### ISSUE TITLE
High Contrast / Dark Theme?

### ISSUE THREAD

**Issue by circulon** [localstack/cockpit#14]
I am a vision impaired user and am really strugging with the Cockpit with its current "Light" Theme.
This is making it extremely difficult to navigate the app and find items on the screen or even to work out how to use those items.

Ideally the app should offer a "Dark" theme like many other apps do these days.
This would probably include
- Dark/Black background
- Lighter (white not pale blue) coloured text and buttons
- In MacOs observing the Users choice of theme (Light/dark) and adjusting as required
- These are just initial thoughts 

This would be very helpful for many users who also struggling with this colour scheme

Thanks for your understanding

**Comment by SimonWallner** [comment]
Hi Kieren!
I am curious to learn more about your specific requirements and what would make for a better user experience in the cockpit. Maybe you could even point us to any good examples or resources that you find helpful.

**Comment by Pive01** [comment]
Closing as this project is now deprecated, please switch to use [LocalStack Desktop](https://github.com/localstack/localstack-desktop) instead.
