### ISSUE TITLE
Feature request: allow Cockpit to detect existing Localstack instances (e.g. from TestContainers)

### ISSUE THREAD

**Issue by ccpulse** [localstack/cockpit#15]
We use localstack extensively using TestContainers, it'd be great if Cockpit could detect the existing running container so we could use it to view logs/check service status etc while debugging.

**Comment by lbedner** [comment]
Came here with basically the same question. Also, in addition to detecting existing containers, it would be nice (unless I'm missing something 🤔 ) to be able to modify some configuration file so you can explicitly point to wherever your localstack is.

**Comment by fmalk** [comment]
Came here with the same question as well. As of today, Cockpit checks local Docker and tries to use image from `latest`, and current latest is a dev build (`1.3.2.dev`), I was hoping to pinpoint to the last stable version `1.3.1` and avoid any issues due to some instability.

**Comment by brianczapiga** [comment]
Current version of Cockpit has links to documentation that say you should be able to use the environment variable IMAGE_NAME (in the configuration in the UI) but this is not working. Always uses the non pro image and also latest.

**Comment by nvachhar** [comment]
I use localstack in a `kind` cluster running on a remote host. Would be nice to be able to port-forward back to my workstation and use cockpit.

**Comment by Pive01** [comment]
Closing as this project is now deprecated, please switch to use [LocalStack Desktop](https://github.com/localstack/localstack-desktop) instead.
