### ISSUE TITLE
Add support for localstack Docker image from other repository (i.e. AWS ECR)

### ISSUE THREAD

**Issue by LaurentGoderre** [localstack/cockpit#16]
Currently it doesn't detect localstack that are crested using image from other registry like AWS ECR

**Comment by ltomes** [comment]
I'm also awaiting this feature. Is this something that can be configured in a .localstack configuration of the home directory?

**Comment by Pive01** [comment]
Closing as this project is now deprecated, please switch to use [LocalStack Desktop](https://github.com/localstack/localstack-desktop) instead.
