### ISSUE TITLE
Why does it automatically download localstack-pro?

### ISSUE THREAD

**Issue by AntonioCS** [localstack/cockpit#17]
I'm using the community version of localstack and when I open cockpit I see this:
![image](https://user-images.githubusercontent.com/1086401/233434738-b2c19d41-0cbf-45bb-b9eb-64c966de85b1.png)
I already have the community edition why do I need download the pro?

**Comment by lukqw** [comment]
Hi there @AntonioCS 👋 
We preemptively download the pro image, next to the community image, to ensure that users can start up a LocalStack Pro instance as well with the cockpit.

**Comment by AntonioCS** [comment]
@lukqw that sounds good in theory but for users that are just using the community version it's a nuisance and an extra image that isn't being used and is just occupying disk space.
I now have to have both images? Why? If I switch to pro I'll download pro until then let me just use the image I'm using.

**Comment by psoares** [comment]
I have the opposite problem. I have a localstack pro license but can't get the localstack/localstack-pro container to work. My splash screen doesn't show it's pulling it.

![image](https://user-images.githubusercontent.com/192243/234037441-20dc5d19-a5ee-4994-8f06-bf31622227c9.png)

**Comment by lukqw** [comment]
@psoares please download the latest cockpit version from here: https://localstack.cloud/products/cockpit/ 
It should then download the pro image accordingly.

@AntonioCS thank you for your input - we have added your request to our backlog and will ensure that the next release will not unnecessarily pull the pro image.

**Comment by psoares** [comment]
@lukqw, despite installing the latest version, (0.2.1), the UI still launches `localstack/localstack` container.
It also ignores my run configuration settings, which I set as:
 ```
LOCALSTACK_API_KEY=xxxxxxxx
DEBUG=1
EC2_VM_MANAGER=docker
PERSISTENCE=1
IMAGE_NAME=localstack/localstack-pro:latest
MAIN_CONTAINER_NAME=my_localstack
```

**Comment by lukqw** [comment]
@psoares 
just to verify: can you see the step of checking for the localstack-pro image on startup of the cockpit?

which version are you seeing in the bottom right corner of the cockpit? this should be v0.2.1
