### ISSUE TITLE
Not working with existing root Docker Daemon 

### ISSUE THREAD

**Issue by DieSchoeneWolke** [localstack/cockpit#19]
Checking Docker
Docker version 24.0.2, build cb74dfc
Could not detect a running Docker daemon. Please make sure that Docker is running.

[2023-06-12 12:03:43.198] [warn]  error: Command failed: docker version
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied

Linux v0.2.1 (beta)

**Comment by Pive01** [comment]
Closing as this project is now deprecated, please switch to use [LocalStack Desktop](https://github.com/localstack/localstack-desktop) instead.
