### ISSUE TITLE
typo: hostname is used for docker inspect instead of localstack_main

### ISSUE THREAD

**Issue by nbaileydev** [localstack/cockpit#21]
LocalStack Cockpit version: v0.2.1
LocalStack version: 2.1.1.dev
LocalStack Docker container id: 2091a5172071
LocalStack build date: 2023-06-26
LocalStack build git hash: 7e1346e0
Docker Daemon: Docker version 24.0.2, build cb74dfc
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 37 (Thirty Seven)
Release:        37
Codename:       ThirtySeven

When running from the console, I see the following error:
```log
10:50:47.128 › stdout: ERROR: '['docker', 'inspect', '--format', '{{json .}}', 'myhostname']': exit code 1; output: b'\nError: No such object: myhostname\n'
{"runtime_version": "2.1.1.dev", "image_tag": "latest", "image_id": 
"a6b86a621a96", "image_created": "2023-06-26T07:01:34", "running": true, 
"container_name": "localstack_main", "container_ip": "172.17.0.2"}

10:50:47.129 › SyntaxError: Unexpected token E in JSON at position 0
    at JSON.parse (<anonymous>)
    at t.parseStatusStdout (/tmp/.mount_LocalSz9URxz/resources/app.asar/dist/main/main.js:14:892681)
    at t.default.getStatus (/tmp/.mount_LocalSz9URxz/resources/app.asar/dist/main/main.js:14:888969)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.default.getAndSendStatus (/tmp/.mount_LocalSz9URxz/resources/app.asar/dist/main/main.js:14:896957)
    at i.handle (/tmp/.mount_LocalSz9URxz/resources/app.asar/dist/main/main.js:14:887466)
    at /tmp/.mount_LocalSz9URxz/resources/app.asar/dist/main/main.js:14:896721
10:50:47.587 › stdout: ERROR: '['docker', 'inspect', '--format', '{{json .}}', 'myhostname']': exit code 1; output: b'\nError: No such object: myhostname\n'
{"runtime_version": "2.1.1.dev", "image_tag": "latest", "image_id": 
"a6b86a621a96", "image_created": "2023-06-26T07:01:34", "running": true, 
"container_name": "localstack_main", "container_ip": "172.17.0.2"}
```

This error reflects what I see if I query docker directly with `docker inspect myhostname`:
```log
[]
Error: No such object: myhostname
```

However, if I use `docker inspect localstack_main` then I see what you're probably looking for.

note: "myhostname" is a substitution for the actual host name

**Comment by nbaileydev** [comment]
If you'd like help on working issues like this, I'm willing to help.

**Comment by Pive01** [comment]
Closing as this project is now deprecated, please switch to use [LocalStack Desktop](https://github.com/localstack/localstack-desktop) instead.
