### ISSUE TITLE
LocalStack cockpit cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by marekzajac-b** [localstack/cockpit#22]
Hey,

It would be nice to register and verify LocalStack Cockpit app within Apple. I use corporate Macbook Pro and I don't want to bypass security settings in order to install Cockpit.

**Comment by Pive01** [comment]
Closing as this project is now deprecated, please switch to use [LocalStack Desktop](https://github.com/localstack/localstack-desktop) instead.
