### ISSUE TITLE
error when opening app

### ISSUE THREAD

**Issue by dalepaul-RL** [localstack/cockpit#5]
receiving the following error when trying to start Macbook version of the app.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/90710559/164544881-1e2827b6-abdb-4fe5-8e5d-a74b759ccf0e.png">

**Comment by thrau** [comment]
thanks for reporting @dalepaul-RL, can you share a bit more? are you using the Intel version of the Cockpit? What Mac version are you on?

**Comment by dalepaul-RL** [comment]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/90710559/164545738-3dbeeec2-0e4f-4eab-b416-42b22f5d2c20.png">

**Comment by dalepaul-RL** [comment]
tried to uninstall and re-install. with no luck. Is there a json config file stored somewhere that I can check/delete?

**Comment by dalepaul-RL** [comment]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/90710559/164546149-da2b65cb-594b-4e83-8ff5-59b871de29c8.png">

**Comment by hurutta** [comment]
Facing the same issue on fedora37, linux kernel `6.0.12-300.fc37.x86_64`
![image](https://user-images.githubusercontent.com/87583138/208763403-474f95b1-7ded-464e-b077-962445e28f5a.png)

**Comment by brainstormtrooper** [comment]
Facing the same issue as hurutta on OpenSUSE kernel 6.2
Cockpit version (only one available on the website) 0.2.0 beta

I see there are screenshots of a version 1.0.0...

**Comment by brainstormtrooper** [comment]
So, I am still facing this issue with cockpit, so I have to do without unfortunately.
I did notice that running `docker inspect localstack/localstack` returns correct info, it this info supposed to be available from localhost? Is there some config value to set so that the correct "object" is inspected?

**Comment by willisjtc** [comment]
I just ran into this issue on Fedora

**Comment by nbaileydev** [comment]
I also ran into this on Fedora.
Cockpit version: 0.2.1
Container Version: 2.1.1.dev (7e134630)

I am seeing these messages in the appimage logs:
```
› error: Command failed: /tmp/.mount_LocalS7Cy5TD/resources/vendor/linux/localstack-packaged-cli/localstack status services --format=json
, stdout: {"error": "could not connect to LocalStack health endpoint at 
http://localhost:4566"}
```

and these in the container logs:
```
INFO --- [   asgi_gw_1] localstack.request.http    : OPTIONS /_localstack/stackinfo => 204
WARN --- [   asgi_gw_0] l.aws.handlers.internal    : Unable to find resource handler for path: /_localstack/stackinfo
INFO --- [   asgi_gw_0] localstack.request.http    : GET /_localstack/stackinfo => 404
INFO --- [   asgi_gw_0] localstack.request.http    : OPTIONS /_localstack/stackinfo => 204
WARN --- [   asgi_gw_1] l.aws.handlers.internal    : Unable to find resource handler for path: /_localstack/stackinfo
INFO --- [   asgi_gw_1] localstack.request.http    : GET /_localstack/stackinfo => 404
```

This happens regardless of whether I start the container before using docker-compose or allow cockpit to create and start it independently.
