### ISSUE TITLE
Error when attempting to open arm64 app on macOS 

### ISSUE THREAD

**Issue by jamieforrest** [localstack/cockpit#6]
After copying the arm64 cockpit app to my Applications folder and attempting to open the app, I get the error:

“LocalStack Cockpit” is damaged and can’t be opened. You should move it to the Trash.

macOS Monterey 12.3.1
MacBook Pro (14-inch, 2021)
Apple M1 Max

app installer: LocalStack Cockpit 0.1.1-arm64.dmg

**Comment by Vizz85** [comment]
Same issue here with an Apple M1 and LocalStack Cockpit 0.1.1-arm64.dmg

**Comment by JEET-RARIO-0291** [comment]
Same issue with an Apple M1 pro.

**Comment by mark-w-325** [comment]
Same issue here

**Comment by MarcelStranak** [comment]
Thank you for the reports. We have removed the M1 version.
Apple (Intel version) provides the same functionality for now. We appreciate the reports.
