### ISSUE TITLE
Setting SERVICES environment variable does not start the specific services

### ISSUE THREAD

**Issue by nishadmenezes** [localstack/cockpit#9]
I tried setting the configuration environment variable for `SERVICES` on windows. It doesn't start the services specified.
![image](https://user-images.githubusercontent.com/5309373/171110798-29163830-6488-4ee2-bda9-872c7b4516a2.png)
![image](https://user-images.githubusercontent.com/5309373/171111166-1df9c424-6a28-490d-bc61-83daeb846a2f.png)

**Comment by MarcelStranak** [comment]
Hello @nishadmenezes,

Thank you for the report. Please have a look at our page with the possible [configurations](https://docs.localstack.cloud/references/configuration). To enable early start of the service, you need to set another environment variable `EAGER_SERVICE_LOADING=1`.  

We do not recommend using this outdated model, as we provide lazy loading of services when necessary.
